# Declarações

* O python é uma linguagem imperativa, baseada em declarações (statements): **expressão, atribuição, chamada de função, definição de função...**

## Expressões

### Números

In [1]:
# Mostrar na tela um número (este é um comentário)
10

10

In [2]:
-3

-3

In [3]:
3.14

3.14

In [4]:
-3 + 2

-1

### Strings (sequências de caracteres)

In [5]:
'maçã'

'maçã'

In [6]:
"maçã"

'maçã'

In [7]:
"meu nome" + " " + "é" + " " + "Nilson"

'meu nome é Nilson'

### Valores booleanos

In [8]:
True

True

In [9]:
False

False

### Listas e dicionários

Python tem três tipos de estruturas embutidas na própria linguagem:
* dicionários (tabelas de hash): `{}`
* listas: `[]`
* tuplas: `()`

In [10]:
[1, 2, 3]

[1, 2, 3]

In [11]:
(1, 2, 3)

(1, 2, 3)

In [12]:
1, 2, 3

(1, 2, 3)

In [ ]:
{'maça': 2, 'banana': 5, 'uva': 2}

## Variáveis e tipos

### Atribuição

Operador de atribuição é `=`. O python é uma linguagem dinamicamente tipada (tipos de variáveis são atribuídos durante o uso).

In [13]:
# declaração de atribuição
x = 1.0
minha_variavel = 12.2

In [14]:
type(x)

float

In [15]:
# o tipo da variável pode mudar
x = 1

In [16]:
type(x)

int

### Tipos fundamentais

In [17]:
x = 1
type(x)

int

In [18]:
x = 1.0
type(x)

float

In [19]:
b1 = True
type(b1)

bool

In [20]:
x = 1.0 - 1.0j
type(x)

complex

In [21]:
print(x) # exibe algo
print(x.real)
print(x.imag)

(1-1j)
1.0
-1.0


In [22]:
# usar uma variável não declarada
type(y)

NameError: name 'y' is not defined

### Conversão de tipos

In [23]:
x = 1.5

print(x, type(x))

1.5 <class 'float'>


In [24]:
x = int(x)

print(x, type(x))

1 <class 'int'>


### Operadores Aritméticos

In [25]:
#Soma
x1 = 2 + 3
print("Soma:", x1)

#Subtração
x2 = 2 - 3
print("Subtração:", x2)

#Multiplicação
x3 = 2 * 3
print("Multiplicação:", x3)

#Divisão
x4 = 10 / 2
print("Divisão:", x4)

#Módulo ou Resto da Divisão
x5 = 11 % 2
print("Módulo ou Resto da Divisão:", x5)

#Exponenciação
x6 = 5 ** 2
print("Exponenciação:", x6)

#Quociente da Dividão
x7 = 9 // 2
print("Quociente da Divisão:", x7)

Soma: 5
Subtração: -1
Multiplicação: 6
Divisão: 5.0
Módulo ou Resto da Divisão: 1
Exponenciação: 25
Quociente da Divisão: 4


### Operadores Relacionais

In [26]:
print(3 == 5)
print(3 > 0)
print(5 != 5)
print(3 >= 3)

False
True
False
True


### Operadores Lógicos

In [27]:
x = 8
y = 6

print(3 > 0 and 5 < 10)
print(x < y or 6 == 7)
print(not(x < y))

True
False
True


## Funções

**Rotina repetitiva**: definimos uma função e, ao chamar a função passando as informações necessárias, a rotina é executada.

In [28]:
abs(-1)

1

In [29]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



### print

In [30]:
print(1)

1


### Definindo funções

In [31]:
# def <nome> (<parametros>):
def soma(a, b):
  return a + b

In [32]:
soma(3, 4)

7

In [33]:
soma("a", 1) # o que aconteceu?

TypeError: can only concatenate str (not "int") to str

## Funções sem nome (unamed functions - lambda function)

Em python é possível criar funções sem nome utilizando a palavra chave `lambda`

In [34]:
f1 = lambda x: x ** 2

# é equivalente a
def f2(x):
  return x ** 2

In [35]:
f1(2), f2(2)

(4, 4)

# Módulos

A maior parte das funcionalidades de python é dada pelos módulos. A biblioteca padrão do python é uma grande coleção de módulos que proveem implementações de utilidades, tais quais **acesso ao sistema operacional, leitura e escrita de arquivos, gerenciamento de texto, etc.**

http://docs.python.org/2/reference/index.html

http://docs.python.org/2/library/

In [36]:
import math # para usar um módulo é necessário realizar a importação

In [37]:
# O import inclui o módulo inteiro e deixa disponível para uso posterior no programa
import math

x = math.cos(2 * math.pi) # função de cossenos e a constante PI
print(x)

1.0


In [38]:
# podemos incluir todos os símbolos de um prefixo, também. Isso evita a necessidade
# de chamar math
from math import *

x = cos(2 * pi)
print(x)

1.0


In [39]:
# podemos, ainda, escolher o que vamos utilizar dos módulso
from math import cos, pi

x = cos(2 * pi)
print(x)

1.0


## Vendo o que um módulo contém

A função `dir` lista os símbolos de um módulo

In [40]:
import math

print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [41]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [42]:
log(10)

2.302585092994046

In [43]:
log(10, 2)

3.3219280948873626

# Estruturas de controle

Utilizadas para controlar o fluxo sequencial de execução do código

## Estrutura Condicional

In [44]:
a = 33
b = 200
if b > a:
    print("b é maior que a")
elif b < a:
    print("b é menor que a")
else:
    print("b é igual a")

b é maior que a


## Repetição

In [45]:
i = 1
while i < 6:
  print(i)
  i += 1 # equivalente a i = i + 1

1
2
3
4
5


In [46]:
cursos = ["Audio/Visual", "Jornalismo", "Publicidade"]
for x in cursos:
  print(x)

Audio/Visual
Jornalismo
Publicidade


# Manipulando dados compostos

Strings, listas e dicionários são tipos compostos. Ou seja, são um "agrupamento" de tipos diferentes.

## Strings

São composições de caracteres

In [47]:
s = "Olá mundo"
type(s)

str

In [48]:
len(s) # o comprimento da string (número de caracteres)

9

In [49]:
# substituir uma substring de uma string com alguma coisa
s2 = s.replace("mundo", "teste")
print(s2)

Olá teste


In [50]:
# podemos acessar caracteres com a indexação
s[0]

'O'

In [51]:
# podemos fazer o slicing: especificar um intervalo de indices
# [inicio:fim], que começa a indexação em 'inicio' e termina em 'fim - 1'
s[0:5]

'Olá m'

In [52]:
s[4:5]

'm'

In [53]:
# se omitir inicio ou fim, o padrão é do início ao fim da string

In [54]:
s[:5]

'Olá m'

In [55]:
s[6:]

'ndo'

In [56]:
s[:]

'Olá mundo'

## Listas

A manipulação é muito similar a strings, exceto que listas podem conter qualquer tipo de dado

In [57]:
l = [1, 2, 3, 4]
print(type(l))
print(l)

<class 'list'>
[1, 2, 3, 4]


In [58]:
print(l)
print(l[1:3])

[1, 2, 3, 4]
[2, 3]


In [59]:
l[0]

1

In [60]:
l = [1, 'a', 1.0] # podem conter quaisquer tipos de dado
print(l)

[1, 'a', 1.0]


In [ ]:
l = [1, [2, 3]] # include outras listas

print(l[0])
print(l[1])

In [61]:
# Listas são úteis para serem utilizadas nos laços for
inicio = 10
fim = 30
passo = 2

range(inicio, fim, passo)

range(10, 30, 2)

In [62]:
list(range(inicio, fim, passo))

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [63]:
list(range(-10, 10))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
l = [1, 2, -3, -1]
l.sort()
print(l)

[-3, -1, 1, 2]


### Adicionando, inserindo, modificando e removendo elementos de listas

In [65]:
l = [] # lista vazia

# adiciona elementos
l.append("A")
l.append("d")
l.append("d")

print(l)

['A', 'd', 'd']


In [66]:
l[1] = "p"
l[2] = "p"

print(l)

['A', 'p', 'p']


In [67]:
l[1:3] = ["d", "d"]
print(l)

['A', 'd', 'd']


In [68]:
# remove um elemento em uma localização especifica
l = ['i', 'n', 's', 'e', 'r', 'i', 'r']

print(l)

del l[6]
print(l)
del l[0]
print(l)

['i', 'n', 's', 'e', 'r', 'i', 'r']
['i', 'n', 's', 'e', 'r', 'i']
['n', 's', 'e', 'r', 'i']


### Tuplas

Tuplas são como listas, exceto que elas são **imutáveis**. Uma vez criadas, não podem ser modificadas.

In [69]:
ponto = (10, 20)
print(ponto, type(ponto))

(10, 20) <class 'tuple'>


In [70]:
ponto = 10, 20 # empacotamento
x, y = ponto # desempacotamento

print(ponto, type(ponto))
print("x = ", x) # separador por vírgula gera uma string concatenada
print("y = ", y)

(10, 20) <class 'tuple'>
x =  10
y =  20


In [71]:
ponto[0] = 20 # diferente de listas, aqui trará um erro

TypeError: 'tuple' object does not support item assignment

### Dicionários

In [72]:
parametros = {"parametro1": 1.0,
              "parametro2": 2.0,
              "parametro3": 3.0}
print(type(parametros))
print(parametros)

<class 'dict'>
{'parametro1': 1.0, 'parametro2': 2.0, 'parametro3': 3.0}


In [73]:
print("parametro1 = " + str(parametros["parametro1"]))
print("parametro2 = " + str(parametros["parametro2"]))
print("parametro3 = " + str(parametros["parametro3"]))

parametro1 = 1.0
parametro2 = 2.0
parametro3 = 3.0


In [74]:
parametros["parametro1"] = "A"
parametros["parametro2"] = "B"

# adiciona uma nova entrada
parametros["parametro4"] = "D"

print("parametro1 = " + str(parametros["parametro1"]))
print("parametro2 = " + str(parametros["parametro2"]))
print("parametro3 = " + str(parametros["parametro3"]))
print("parametro4 = " + str(parametros["parametro4"]))

parametro1 = A
parametro2 = B
parametro3 = 3.0
parametro4 = D


# Arrays

A biblioteca mais utilizada para representar vetores (arrays) é o NumPy. A biblioteca é muito útil para várias funções matemáticas, desde coisas mais simples a coisas mais complexas. Uma característica é que é um módulo bastante eficiente para representar agrupamentos de dados (arrays, matrizes e estruturas de dados de alta dimensionalidade)

In [75]:
import numpy as np

## Criando arrays

In [76]:
import numpy as np

v = np.array([1, 2, 3, 4])
print(v)
print(type(v))

[1 2 3 4]
<class 'numpy.ndarray'>


In [77]:
v.shape

(4,)

In [78]:
M = np.array([[1, 2], [3, 4]])
print(M)
print(type(M))
print(M.shape)
print(M.size)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
(2, 2)
4


In [79]:
M.dtype

dtype('int32')

In [80]:
M[0, 0] = "olá"

ValueError: invalid literal for int() with base 10: 'olá'

## Números aleatórios

In [81]:
from numpy import random

In [82]:
v = random.rand(5, 5) # valores aleatórios uniformes entre [0, 1]
print(v)
print(type(v))

[[0.05293292 0.22762699 0.16818506 0.75008461 0.06853419]
 [0.59065715 0.41537035 0.91136236 0.50601276 0.27309142]
 [0.79252475 0.26262082 0.3687975  0.35239527 0.12360962]
 [0.80828704 0.31778892 0.92589359 0.84909285 0.98091114]
 [0.29845993 0.80039738 0.48305513 0.03252287 0.62777496]]
<class 'numpy.ndarray'>


In [83]:
zeros_v = np.zeros((3, 3))
uns_v = np.ones((3, 3))

print(zeros_v)
print(uns_v)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Manipulando arrays

In [84]:
v = random.rand(5, 5)
v

array([[0.68218205, 0.75557392, 0.28260456, 0.61594017, 0.69889055],
       [0.67124663, 0.06501598, 0.72654508, 0.48156251, 0.31988966],
       [0.31764402, 0.58734118, 0.83546832, 0.1546297 , 0.43978268],
       [0.10548324, 0.49952226, 0.88304279, 0.53166994, 0.02550301],
       [0.57992162, 0.27665009, 0.74111809, 0.58619445, 0.84204943]])

In [85]:
v[0, 0]

0.6821820503927756

In [86]:
print(v[0])
print(v[0, :])

[0.68218205 0.75557392 0.28260456 0.61594017 0.69889055]
[0.68218205 0.75557392 0.28260456 0.61594017 0.69889055]


In [87]:
v[0, 0] = 1
v

array([[1.        , 0.75557392, 0.28260456, 0.61594017, 0.69889055],
       [0.67124663, 0.06501598, 0.72654508, 0.48156251, 0.31988966],
       [0.31764402, 0.58734118, 0.83546832, 0.1546297 , 0.43978268],
       [0.10548324, 0.49952226, 0.88304279, 0.53166994, 0.02550301],
       [0.57992162, 0.27665009, 0.74111809, 0.58619445, 0.84204943]])

In [88]:
v[1, :] = -1
v

array([[ 1.        ,  0.75557392,  0.28260456,  0.61594017,  0.69889055],
       [-1.        , -1.        , -1.        , -1.        , -1.        ],
       [ 0.31764402,  0.58734118,  0.83546832,  0.1546297 ,  0.43978268],
       [ 0.10548324,  0.49952226,  0.88304279,  0.53166994,  0.02550301],
       [ 0.57992162,  0.27665009,  0.74111809,  0.58619445,  0.84204943]])

In [89]:
A = np.array([1, 2, 3, 4, 5])
A[1:3]

array([2, 3])

In [90]:
A[1:3] = [-2, -3]
A

array([ 1, -2, -3,  4,  5])

# Exercícios

1. Escreva um programa que calcula a área de um círculo baseado na entrada do usuário pelo teclado.

Dica 1: utilize a função `input`. Verfique o tipo de valor que a função `input` retorna e, se necessário, faça a conversão da entrada para um número decimal com a função `float`.
Dica 2: a área de um círculo é dada pela fórmula $\pi*r^2$

In [92]:
def area_circle(radius):
    """Calculates the area of a circle based on the radius.
    
    Parameters
    ---------
    radius: radius of the circumference, only accepts int or float.
    
    Returns
    ---------
    area: area of the circumference. The area is measured in the same unit
    as the radius squared.
    """
    area = np.pi * radius ** 2
    return area

# Para uma circunferência com 3 metros de raio:
area_circle(3) # A área será medida em metros quadrados

28.274333882308138

2. Escreva um programa python que aceita um número inteiro `n` e calcula o valor de `n + nn + nnn`.

In [93]:
def func(n):
    """Calculates a number based on the formula n + n**2 + n**3.
    
    Parameters
    ---------
    n: any number, accepts int or float.
    
    Returns
    ---------
    soma: result of the formula.
    """
    soma = n + n**2 + n**3
    return soma

# n como float:
print(func(2.71))

# n como int:
print(func(5))

29.956611000000002
155


3. Faça um programa para calcular a diferença entre um número digitado via `input` e `17`. Se o número for maior do que `17`, retorne o dobro do valor absoluto da diferença.

In [104]:
def func_17():
    number = float(input("Digite um número: "))
    if number > 17:
        dif = number - 17
        result = 2 * dif
        text = f"O dobro da diferença entre {number} e 17 é igual a {result}"
        print(text)
        return result
    else:
        raise ValueError("Digite um número maior que 17.")
    return

# Tentando o erro:
func_17()

Digite um número: 6


ValueError: Digite um número maior que 17.

In [105]:
# Usando a função do jeito correto:
func_17()

Digite um número: 23.5
O dobro da diferença entre 23.5 e 17 é igual a 13.0


13.0

4. Faça um programa python que encontre a quantidade de divisores de um número inteiro digitado pelo usuário.

In [109]:
def divisors(n:int):
    result = []
    for i in range(1, int(sqrt(n))+1):
        if n % i == 0:
            result.append(i)
            result.append(n//i)
    result.sort()
    number_divisors = len(result)
    return number_divisors

divisors(24)

8

5. Escreva um programa para verificar se um número é primo.

Lembre-se: um número natural é primo se tem apenas dois divisores.

In [110]:
divisors(17)

2

In [111]:
def prime(n:int):
    if divisors(n) == 2:
        print(f"{n} é um número primo.")
    else:
        raise ValueError(f"{n} não é um número primo.")
    return

# Número não primo:
prime(64)

ValueError: 64 não é um número primo.

In [113]:
# Número primo:
prime(47)

47 é um número primo.


6. Escreva um programa que some todos os números de uma lista dada: `[1, -2, 8, 5, 3]`

In [100]:
my_list = [1, -2, 8, 5, 3]

def sum_of_list(numbers_list):
    total = sum(numbers_list)
    return total

sum_of_list(my_list)

15

7. Escreva um programa python que encontre o menor elemento de uma lista.

In [103]:
def lowest(numbers_list):
    numbers_list.sort()
    return numbers_list[0]

lowest(my_list)

-2